name: Main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Packages/**'
      - 'ProjectSettings/**'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - '.editorconfig'
      - 'LICENSE'
      - '**.md'
      - '**.yml'
      - '**.txt'
      - '**.ps1'
  push:
    branches:
      - main
    paths-ignore:
      - 'Packages/**'
      - 'ProjectSettings/**'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - '.editorconfig'
      - 'LICENSE'
      - '**.md'
      - '**.yml'
      - '**.txt'
      - '**.ps1'
  
jobs:
  Release:
    name: Semantic Release
    if: github.event_name == 'push'
    uses: ./.github/workflows/semantic.yml
    secrets: inherit